### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by mglowacki100** [alan-turing-institute/ptype-dmkd#1]
As far I understand `greenery` is required library, but not package itself. Any chance for `pip install ...`?
Btw. very interesting project.

**Comment by tahaceritli** [comment]
Thanks for the question and the comment. 

Yes, greenery is a required library that you need to install to use our method. Currently, we do not have a python package of this work that you can install through pip.

**Comment by rolyp** [comment]
@mglowacki100 Package now pip-installable via https://pypi.org/project/ptype/.
