### ISSUE TITLE
Output discrepancy with column_type_predictions.json

### ISSUE THREAD

**Issue by rolyp** [alan-turing-institute/ptype-dmkd#7]
- [x] [BOM character](https://en.wikipedia.org/wiki/Byte_order_mark) at beginning of `OBJECTID` in `tests/column_type_predictions.json`
- [x] prettyprint JSON output to allow line diffing

**Comment by tahaceritli** [comment]
I have fixed these two bugs and pushed it to master (see https://github.com/alan-turing-institute/ptype-dmkd/commit/5e8470e837d88f476baabffd0cc218790395dd37)
