### ISSUE TITLE
Publish package to PyPI

### ISSUE THREAD

**Issue by rolyp** [alan-turing-institute/ptype-dmkd#9]
Automate publishing to PyPI using `develop` and `master` pattern.
- [x] test upload to TestPyPI
- [x] `publish.sh` script that takes PyPI password as argument
- [x] add`pypi-password` secret to repo
- [x] GitHub job to run `publish.sh` using `pypi-password`
- [x] new `release` branch; Publish job should only run on `release`
- [x] new `develop` branch as default 
- <s>add `upload-artifact` step to store `dist` folder as artifact</s>
- <s>add `download-artifact` step to publish job</s>
- <s>missing project description</s>
- `HTTPError: 400 Client Error: File already exists`
  - [x] bump version number in `setup.py` (probably using [bump2version](https://pypi.org/project/bump2version/)) 
- `HTTPError: 400 Client Error: Only one sdist may be uploaded per release`
  - [x] clean `dist` directory otherwise will end up with multiple source distributions
- [x] `git tag` with version number
- [x] `git push` to push changes to version number in `setup.py` and `.bumpversion.cfg`
- <s>only publish if [latest commit is tagged](https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/)</s>
- switch from TestPyPI to PyPI
  - [x] PyPI secret in repo
  - [x] parameterise `publish.sh` on `pypi` or `testpypi`
  - [x] `build-test-publish.yml` to use `pypi` by default
- [x] top-level Bash script to emulate GitHub workflow (with appropriate password)
- [x] extract common Python `virtualenv` gubbins

**Comment by GjjvdBurg** [comment]
As a quick comment, you might be interested in the [release script](https://github.com/alan-turing-institute/CleverCSV/blob/master/make_release.py) I use for CleverCSV and other packages to semi-automate the release process.

**Comment by rolyp** [comment]
@GjjvdBurg This is super-useful, thanks!
